[project]
name = "taskich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sayhelloartemka", email = "107796896+SweetSt@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.142.2",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.1.4",
]

[project.scripts]
taskich = "taskich:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
